#cloud-config

packages:
  - git

runcmd:
  # Trust the microsoft repository
  - |
    wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb
  # Install the .NET SDK (not ment for server)
  - |
    sudo apt-get update && \
    sudo apt-get install -y dotnet-sdk-9.0

  # Clone the repository
  - |
    mkdir /app-repo
    git clone https://github.com/LarsGJobloop/2025-08-12-iac-server-setup.git /app-repo

  # Build the project
  - |
    cd /app-repo
    dotnet restore
    dotnet build --configuration Release --output out src/Api.csproj

  # Start the server
