#cloud-config

runcmd:
  # Trust the microsoft repository
  - |
    wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb
  # Install the .NET SDK (not ment for server)
  - |
    sudo apt-get update && \
    sudo apt-get install -y dotnet-sdk-9.0
